name: Test Gsheet json
on: 
  push:
    branches:
      - 'main'
jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      msgoutput: ${{ steps.msg.outputs.var }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - id: 'update_worksheet'
        uses: jroehl/gsheet.action@v1.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: ${{ secrets.TEST_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getWorksheet", "args": { "worksheetTitle": "workingon" } },
              { "command": "getData", "args": { "minRow": 66 , "minCol": 1 } }
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
      
      - name: dump results
        env:
          #  the output of the action can be found in ${{ steps.update_worksheet.outputs.results }}
          RESULTS: ${{ steps.update_worksheet.outputs.results }}
        run: |
          echo "$RESULTS" > result.json